### ISSUE TITLE
Can I use the repo to merge/concat multiple audio files?

### ISSUE THREAD

**Issue by zydjohnHotmail** [beardgame/audio#55]
Hello:
I have some audio files (in AAC format), which are extracted by FFMPEG from one video (MP4 format) file.  Let’s say, I have 2 of such audio files: (C:\Audios\1.aac and C:\Audios\2.aac), I want to merge or concat them into one audio file: C:\Audios\merge.aac.
Can I use the repo to do this?
If yes, please share some C# code.  I am using Visual Studio 2022 for targeting .NET 6.0 on Windows 10.
I can use FFMPEG to do this, unfortunately, FFMPEG is rather bad in processing audio files.  For example, if the original video file has the duration of 1 minute, the audio file extracted from the video has never has the duration of 1 minute, it could be something like: 1.5 minute or others.  Any way, it is not suitable for production.
Let me know if I can use the repo to do the job.
Thanks,

**Comment by tomrijnbeek** [comment]
Hey,

This library is aimed to assist in playing audio, and some rudimentary real-time manipulation of audio streams. That means that offline processing, as you want to do here by concatenating files, isn't considered a use case of this library.

If you were using WAV files, you could perhaps use parts of this library, and OGG support is planned (#8), but writing files is not something we have as a planned feature. In either case, at this time, there is no method of decoding AAC files, so manipulating the underlying sound data is not possible in this repository anyway. It sounds like a library such as https://github.com/naudio/NAudio would be more suited to your needs.
